# Defining Data Type through Scalars

In [1]:
anA = chr(65)
print(type(anA))

<class 'str'>


In [2]:
from fractions import Fraction
x = Fraction(2, 3)
print(x)
print(type(x))

2/3
<class 'fractions.Fraction'>


# Creating Organized Data with Vectors

## Defining a vector

In [3]:
import numpy as np

In [4]:
myVect1 = np.array([1, 2, 3, 4])
print(myVect1)
myVect2 = np.arange(1, 10, 2)
print(myVect2)

[1 2 3 4]
[1 3 5 7 9]


In [5]:
myVect3 = np.array(np.int16([1, 2, 3, 4]))
print(myVect3)
print(type(myVect3))
print(type(myVect3[0]))

[1 2 3 4]
<class 'numpy.ndarray'>
<class 'numpy.int16'>


## Creating vectors of a specific type

In [6]:
myVect4 = np.ones(4, dtype=np.int16)
print(myVect4)

[1 1 1 1]


## Performing math on vectors

In [7]:
print(myVect1 + 1)

[2 3 4 5]


In [8]:
print(myVect1 - 1)

[0 1 2 3]


In [9]:
print(2 ** myVect1)

[ 2  4  8 16]


In [10]:
myVect5 = [1, 2, 3, 4]
print(type(myVect5[0]))
print(type((2 ** np.array(myVect5))[0]))

<class 'int'>
<class 'numpy.int32'>


## Performing logical and comparison tasks on vectors

In [11]:
a = np.array([1, 2, 3, 4])
b = np.array([2, 2, 4, 4])

print(a == b)
print(a < b)

[False  True False  True]
[ True False  True False]


In [12]:
a = np.array([True, False, True, False])
b = np.array([True, True, False, False])

print(np.logical_or(a, b))
print(np.logical_and(a, b))
print(np.logical_not(a))
print(np.logical_xor(a, b))

[ True  True  True False]
[ True False False False]
[False  True False  True]
[False  True  True False]


## Multiplying vectors

In [13]:
myVect = np.array([1, 2, 3, 4])
print(myVect * myVect)
print(np.multiply(myVect, myVect))

[ 1  4  9 16]
[ 1  4  9 16]


In [14]:
print(myVect.dot(myVect))

30


# Creating and Using Matrices

## Creating a matrix

In [15]:
myMatrix1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(myMatrix1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
print(myMatrix1[0, 0])

1


In [17]:
myMatrix2 = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(myMatrix2)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [18]:
print(myMatrix2[0, 1, 1])

4


## Creating matrices of a specific type

In [19]:
myMatrix3 = np.ones([4,4], dtype=np.int32)
print(myMatrix3)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [20]:
myMatrix4 = np.ones([4,4,4], dtype=np.bool)
print(myMatrix4)

[[[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]]


## Using the matrix class

In [21]:
myMatrix5 = np.mat([[1,2,3], [4,5,6], [7,8,9]])
print(myMatrix5)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
print(np.asmatrix(myMatrix3))

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


## Performing matrix multiplication

In [23]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6]])

print(a*b)

[[ 1  4  9]
 [16 25 36]]


In [24]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3,4],[3,4,5,6],[5,6,7,8]])

print(a.dot(b))

[[22 28 34 40]
 [49 64 79 94]]


In [25]:
a = np.mat([[1,2,3],[4,5,6]])
b = np.mat([[1,2,3,4],[3,4,5,6],[5,6,7,8]])

print(a*b)

[[22 28 34 40]
 [49 64 79 94]]


## Executing advanced matrix operations

In [26]:
changeIt = np.array([1,2,3,4,5,6,7,8])

print(changeIt)
print()
print(changeIt.reshape(2,4))
print()
print(changeIt.reshape(2,2,2))

[1 2 3 4 5 6 7 8]

[[1 2 3 4]
 [5 6 7 8]]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [27]:
changeIt2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(np.transpose(changeIt2))

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [28]:
print(np.identity(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [29]:
a = np.array([[1,2], [3,4]])
b = np.linalg.inv(a)

print(np.allclose(np.dot(a,b), np.identity(2)))

True


# Extending Analysis to Tensors

In [30]:
inputs = np.array([5, 10, 15])
weights = np.array([[.5,.2,-1], [.3,.4,.1], [-.2,.1,.3]])
result = np.dot(inputs, weights)
print(result)

[2.5 6.5 0.5]


# Using Vectorization Effectively

In [31]:
def doAdd(a, b):
    return a + b

vectAdd = np.vectorize(doAdd)

print(vectAdd([1, 2, 3, 4], [1, 2, 3, 4]))

[2 4 6 8]


# Selecting and Shaping Data

## Slicing rows

In [32]:
x = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9],],
             [[11,12,13], [14,15,16], [17,18,19],],
             [[21,22,23], [24,25,26], [27,28,29]]])
print(x[1])

[[11 12 13]
 [14 15 16]
 [17 18 19]]


## Slicing columns

In [33]:
x = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9],],
             [[11,12,13], [14,15,16], [17,18,19],],
             [[21,22,23], [24,25,26], [27,28,29]]])
print(x[:,1])

[[ 4  5  6]
 [14 15 16]
 [24 25 26]]


## Dicing

In [34]:
x = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9],],
             [[11,12,13], [14,15,16], [17,18,19],],
             [[21,22,23], [24,25,26], [27,28,29]]])
print(x[1,1])
print(x[:,1,1])
print(x[1,:,1])
print()
print(x[1:2, 1:2])

[14 15 16]
[ 5 15 25]
[12 15 18]

[[[14 15 16]]]


## Concatenating

### Adding new cases and variables

In [35]:
import pandas as pd

df = pd.DataFrame({'A': [2,3,1],
                   'B': [1,2,3],
                   'C': [5,3,4]})

df1 = pd.DataFrame({'A': [4],
                    'B': [4],
                    'C': [4]})

df = df.append(df1)
df = df.reset_index(drop=True)
print(df)

df.loc[df.last_valid_index() + 1] = [5, 5, 5]
print()
print(df)

df2 = pd.DataFrame({'D': [1, 2, 3, 4, 5]})

df = pd.DataFrame.join(df, df2)
print()
print(df)

   A  B  C
0  2  1  5
1  3  2  3
2  1  3  4
3  4  4  4

   A  B  C
0  2  1  5
1  3  2  3
2  1  3  4
3  4  4  4
4  5  5  5

   A  B  C  D
0  2  1  5  1
1  3  2  3  2
2  1  3  4  3
3  4  4  4  4
4  5  5  5  5


### Removing data

In [36]:
import pandas as pd

df = pd.DataFrame({'A': [2,3,1],
                   'B': [1,2,3],
                   'C': [5,3,4]})

df = df.drop(df.index[[1]])
print(df)

df = df.drop('B', 1)
print()
print(df)

   A  B  C
0  2  1  5
2  1  3  4

   A  C
0  2  5
2  1  4


### Sorting and shuffling

In [37]:
import pandas as pd
import numpy as np

df = pd.DataFrame({'A': [2,1,2,3,3,5,4],
                   'B': [1,2,3,5,4,2,5],
                   'C': [5,3,4,1,1,2,3]})

df = df.sort_values(by=['A', 'B'], ascending=[True, True])
df = df.reset_index(drop=True)
print(df)

index = df.index.tolist()
np.random.shuffle(index)
df = df.loc[df.index[index]]
df = df.reset_index(drop=True)
print()
print(df)

   A  B  C
0  1  2  3
1  2  1  5
2  2  3  4
3  3  4  1
4  3  5  1
5  4  5  3
6  5  2  2

   A  B  C
0  5  2  2
1  3  5  1
2  1  2  3
3  3  4  1
4  2  3  4
5  2  1  5
6  4  5  3


## Aggregating

In [38]:
import pandas as pd

df = pd.DataFrame({'Map': [0,0,0,1,1,2,2],
                   'Values': [1,2,3,5,4,2,5]})

df['S'] = df.groupby('Map')['Values'].transform(np.sum)
df['M'] = df.groupby('Map')['Values'].transform(np.mean)
df['V'] = df.groupby('Map')['Values'].transform(np.var)

print(df)

   Map  Values  S    M    V
0    0       1  6  2.0  1.0
1    0       2  6  2.0  1.0
2    0       3  6  2.0  1.0
3    1       5  9  4.5  0.5
4    1       4  9  4.5  0.5
5    2       2  7  3.5  4.5
6    2       5  7  3.5  4.5


# Working with Trees

## Building a tree

In [39]:
class binaryTree:
    def __init__(self, nodeData, left=None, right=None):
        self.nodeData = nodeData
        self.left  = left
        self.right = right

    def __str__(self):
        return str(self.nodeData)

In [40]:
tree = binaryTree("Root")
BranchA = binaryTree("Branch A")
BranchB = binaryTree("Branch B")
tree.left = BranchA
tree.right = BranchB

LeafC = binaryTree("Leaf C")
LeafD = binaryTree("Leaf D")
LeafE = binaryTree("Leaf E")
LeafF = binaryTree("Leaf F")
BranchA.left = LeafC
BranchA.right = LeafD
BranchB.left = LeafE
BranchB.right = LeafF

In [41]:
def traverse(tree):
    if tree.left != None:
        traverse(tree.left)
    if tree.right != None:
        traverse(tree.right)
    print(tree.nodeData)
    
traverse(tree)

Leaf C
Leaf D
Branch A
Leaf E
Leaf F
Branch B
Root


# Representing Relations in a Graph

## Arranging graphs

In [42]:
graph = {'A': ['B', 'F'],
         'B': ['A', 'C'],
         'C': ['B', 'D'],
         'D': ['C', 'E'],
         'E': ['D', 'F'],
         'F': ['E', 'A']}

In [43]:
def find_path(graph, start, end, path=[]):
        path = path + [start]
        
        if start == end:
            print("Ending")
            return path
        
        for node in graph[start]:
            print("Checking Node ", node)
            
            if node not in path:
                print("Path so far ", path)
                
                newp = find_path(graph, node, end, path)
                if newp:
                    return newp

find_path(graph, 'B', 'E')

Checking Node  A
Path so far  ['B']
Checking Node  B
Checking Node  F
Path so far  ['B', 'A']
Checking Node  E
Path so far  ['B', 'A', 'F']
Ending


['B', 'A', 'F', 'E']